# Generated by Django 3.2.5 on 2021-07-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('address_line_1', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, default='')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gender')),
            ],
        ),
    ]
